services:
    # docker compose up --build --watch
    demo:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - USER_ID=1000
                - GROUP_ID=1000
        command: bash -c 'uv sync --locked; uv tree; uv run main.py; sleep infinity'
        user: "1000"
        tty: true
        develop:
            watch:
                - action: sync+restart
                  path: .
                  target: /app
                  ignore:
                    - "__pycache__/"
                    - "__pycache__/"
                    - ".git/"
                    - ".venv/"
                    - ".vscode/"
                    - "*.egg-info"
                    - "*.md"
                    - "*.py[oc]"
                    - "*.pyc"
                    - "build/"
                    - "dist/"
                    - "wheels/"
