[project]
    dependencies    = ["digital-rf>=2.6.9", "loguru>=0.7.3", "numpy>=2.2.0"]
    description     = "Add your description here"
    name            = "drf-tests"
    readme          = "README.md"
    requires-python = ">=3.13"
    version         = "0.1.0"
