[project]
name = "drf-tests"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "digital-rf>=2.6.9",
    "loguru>=0.7.3",
    "numpy>=2.2.0",
]
